version: '3.4'

services:
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    ports: 
      - 9411:9411
    depends_on:
      - rabbit-mq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672 
    networks:
      - junior-network
  
  rabbit-mq:
    image: rabbitmq/zipkin:3.8.14-management
    ports: 
      - 5672:5672
      - 15672:15672
    networks:
      - junior-network      

  cambio-db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: cambio_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3309
    ports: 
      - 3309:3309
    expose:
      - 3309
    networks:
      - junior-network   

  book-db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: book_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3310
    ports: 
      - 3310:3310
    expose:
      - 3310
    networks:
      - junior-network   

  naming-server:
    image: lpjunior00/naming-server:0.0.1-SNAPSHOT
    ports: 
      - 8761:8761
    networks:
      - junior-network

  api-gateway:
    image: lpjunior00/api-gateway:0.0.1-SNAPSHOT 
    ports: 
      - 8765:8765
    depends_on: 
      - naming-server
      - rabbit-mq
    environment: 
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672 
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - junior-network 

  cambio-service:
    image: lpjunior00/cambio-service
    build:
      context: .
      dockerfile: 05-cambio-service/Dockerfile
    restart: always
    environment: 
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
      FLYWAY.URL: jdbc:mysql://cambio-db:3308/cambio_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      FLYWAY.USER: root
      FLYWAY.PASSWORD: admin123
    ports: 
      - 8000:8000
    networks:
      - junior-network 
    depends_on: 
      - naming-server
      - cambio-db
      - rabbit-mq    

  book-service:
    image: lpjunior00/book-service
    build:
      context: .
      dockerfile: 05-book-service/Dockerfile
    restart: always
    environment: 
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
      FLYWAY.URL: jdbc:mysql://book-db:3310/book_service?useSSL=false&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      FLYWAY.USER: root
      FLYWAY.PASSWORD: admin123
    ports: 
      - 8100:8100
    networks:
      - junior-network 
    depends_on: 
      - naming-server
      - book-db
      - rabbit-mq

networks:
  junior-network:
    driver: bridge      